[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/de"
  to = "/de.html"
  status = 200

[[redirects]]
  from = "/tr"
  to = "/tr.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
